=== 0000duck/scilab/scilab/modules/functions/xml/gateway.dtd
<!ELEMENT GATEWAY (META?,PRIMITIVE*)>

<!ELEMENT META (#PCDATA)>

<!ATTLIST META 
CATEGORY 	CDATA 	"Scilab Gateway" 	 
VERSION_SCI 	CDATA 	"5.0" 	 
VERSION_DOC 	CDATA 	"1.0" 	 
AUTHOR 	CDATA 	"Allan CORNET INRIA 2007" 	 
 >

<!ELEMENT PRIMITIVE (GATEWAY_ID,PRIMITIVE_ID,PRIMITIVE_NAME)>

<!ELEMENT GATEWAY_ID (#PCDATA)>
<!ELEMENT PRIMITIVE_ID (#PCDATA)>
<!ELEMENT PRIMITIVE_NAME (#PCDATA)>

=== 0000duck/scilab/scilab/modules/shell/sci_gateway/shell_gateway.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!DOCTYPE GATEWAY SYSTEM "../../functions/xml/gateway.dtd">
<GATEWAY name="shell">
<!-- =================== -->
<!--
 Scilab
 Interface description. In this file, we define the list of the function which
 will be available into Scilab and the link to the "native" function.

 gatewayId is the position in the hashtable 'Interfaces' defined in the
 file SCI/modules/core/src/c/callinterf.h

 primitiveId is the position in the hashtable '<module>Table Tab[]' defined
 in the file modules/<module>/sci_gateway/c/gw_<module>.c

 primitiveName is the name of the Scilab function

 @author Allan CORNET
 @date INRIA 2007
 ===================
 Don't touch if you do not know what you are doing
-->
<!-- =================== -->
<PRIMITIVE gatewayId="53" primitiveId="1" primitiveName="clc"/>
<PRIMITIVE gatewayId="53" primitiveId="2" primitiveName="tohome"/>
<PRIMITIVE gatewayId="53" primitiveId="3" primitiveName="loadhistory" />
<PRIMITIVE gatewayId="53" primitiveId="4" primitiveName="savehistory" />
<PRIMITIVE gatewayId="53" primitiveId="5" primitiveName="gethistory" />
<PRIMITIVE gatewayId="53" primitiveId="6" primitiveName="resethistory" />
<PRIMITIVE gatewayId="53" primitiveId="7" primitiveName="displayhistory" />  
<PRIMITIVE gatewayId="53" primitiveId="8" primitiveName="addhistory" />  
<PRIMITIVE gatewayId="53" primitiveId="9" primitiveName="saveconsecutivecommands" />  
<PRIMITIVE gatewayId="53" primitiveId="10" primitiveName="saveafterncommands" />
<PRIMITIVE gatewayId="53" primitiveId="11" primitiveName="gethistoryfile" />
<PRIMITIVE gatewayId="53" primitiveId="12" primitiveName="sethistoryfile" />
<PRIMITIVE gatewayId="53" primitiveId="13" primitiveName="removelinehistory" />
<PRIMITIVE gatewayId="53" primitiveId="14" primitiveName="historysize" />
</GATEWAY>
